trigger:
  - develop
  - master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)./yarn

stages:
- stage: Build
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.6.0'
        displayName: 'Install Node.js'

      - task: CacheBeta@0
        inputs:
          key: |
            yarn
            $(Agent.OS)
            $(Build.SourcesDirectory)/yarn.lock
          path: $(YARN_CACHE_FOLDER)
        displayName: 'Cache Yarn folders'

      - script: |
          yarn
          yarn build
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'npm install and build'

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.SourcesDirectory)/build
          artifact: Build

- stage: deploy
  jobs:
    - job: deploy
    - deployment: DeployJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: dev
      displayName: Deploy to Netlify
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  yarn deploy
                env:
                  NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    # - script: |
#     yarn deploy
#   workingDirectory: $(Build.SourcesDirectory)
#   env:
#     NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
#   displayName: 'Deploy to netlify'
