# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)./yarn

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.6.0'
  displayName: 'Install Node.js'

- task: CacheBeta@0
  inputs:
    key: |
      yarn
      $(Agent.OS)
      $(Build.SourcesDirectory)/yarn.lock
    path: $(YARN_CACHE_FOLDER)
  displayName: 'Cache Yarn folders'


- script: |
    yarn
    yarn build
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'npm install and build'

- script: |
    yarn deploy
  workingDirectory: $(Build.SourcesDirectory)
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
  displayName: 'Deploy to netlify'
